### ISSUE TITLE
remove concatenated file localforage_adapter.js

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/ember-localforage-adapter#10]
it should be safe to remove localforage_adapter.js which is in the root of the project

**Comment by iamolivinius** [comment]
Actually I found this file pretty useful in case I wanted to create and share a demo on jsbin.

Would it be possible to add a dist folder with a concatenated/transpiled UMD module?

**Comment by frederikbosch** [comment]
See the 0.5x releases. The file is still there. But I guess releasing a new version of the 0.6x will help you more. Sorry for the delay on that one.
