### ISSUE TITLE
Routes not loading updated attributes

### ISSUE THREAD

**Issue by zshnr** [genkgo/ember-localforage-adapter#28]
I’m prototyping a store front. I’m loading all the product model data by pushing it to localstorage (using the localforage adapter) in the application route when the app starts for the first time:

adapters/application.js

    import LFAdapter from 'ember-localforage-adapter/adapters/localforage';

    export default LFAdapter.extend({
       shouldReloadAll: function() {
           return true;
        }
     });

routes/application.js

    import Ember from 'ember';

    export default Ember.Route.extend({
      model: function() {
        this.store.push({
          data: {
            id: '0',
            type: 'product',
            attributes: {
              "name": "Shoes",
              "price": 100,
              "quantityInStock": 2,
              "isOnSale": false
            }
          }
        });
    });

Now, on the index route I change the attribute (like say `isOnSale`) by pressing a button that saves it to localstorage using `.save()`

The changes persist just fine on the index route, but when I goto another route (say /sale), the `isOnSale` that is shown is the old one that was pushed in the initialization of the app, not the updated one from store.

The code for the other route is: 

routes/sale.js

    import Ember from 'ember';

    export default Ember.Route.extend({
      model: function(){
          return this.store.filter('product', function(product) {
              return product.get('isOnSale');
          });
      }
    });

Is this a problem with the adapter?

**Comment by frederikbosch** [comment]
@zshnr I believe shouldReloadAll is a method from Ember Data 1.13. This library is not compatible yet with this version. You can find a branch where I started making it compatible, but that was before the [recently published blogpost](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html) on the changes made in 1.13.

With that blogpost it should be more clear how to upgrade the adapter. If you would like to help with the compatibility, please go ahaed :)

**Comment by zshnr** [comment]
@frederikbosch ah, I had a feeling that is what was breaking. Thanks a lot for the clarification :)

I would love to help you with this, unfortunately I'm not only a junior Ember developer, I'm a junior developer. I have no idea where to start helping you even though I would really like to.

**Comment by zshnr** [comment]
@frederikbosch So I changed ember-data to 1.0.0.beta-18 and still the same issue. (I removed the `shouldReloadAll` hook from adapter.js the rest of the code is still the same.

I noticed though that this problem is with using the filter method. If I use the `find` method, then the data loaded on the other route is the updated data. 

Is there any way I can filter data without using the `filter` method? thanks a lot!

**Comment by frederikbosch** [comment]
@zshnr Yes there is. From the top of my head.

```js
export default Ember.Route.extend({

setupController:  function (controller, model) {
this._super(controller, model);
controller.set('filtered', model.filterBy('isOnSale', true));
}

model: function () {
return this.store.find('product');
}
});
```

**Comment by frederikbosch** [comment]
@zshnr I will have a look at the ```filter``` method. Which version of Ember are you using? Be aware of the fact [that filter will be deprecated in Ember 2.0.0](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_ds-store-filter-moved-to-an-addon) and moved to an addon.

**Comment by zshnr** [comment]
@frederikbosch I downgraded to: `ember: 1.12.0` & `ember-data 1.0.0.beta18`. Thanks a lot for checking it out & the heads up on the impending deprecation :)

**Comment by zshnr** [comment]
@frederikbosch missed your previous post completely, let me try that. Thanks!

**Comment by frederikbosch** [comment]
@zshnr No problem. Will leave this issue open until I have created a test that shows the problem or proves that the problem must on your side.

**Comment by frederikbosch** [comment]
@zshnr The issue on the ```store.find``` method, is that still Ember Data 1.13? Or did your downgrade to a 1.0 beta x?

**Comment by zshnr** [comment]
store.find works on 1.0.beta.18. But it breaks in 1.13.2 (that is the one I tried). It was store.filter that was still breaking in 1.0.beta.18

**Comment by frederikbosch** [comment]
@zshnr The behaviour of the adapter is correct for ```store.filter``` in 1.0 beta 18. Do not forget [to pass a query](http://emberjs.com/api/data/classes/DS.Store.html#method_filter), otherwise Ember Data will [not ask the adapter to lookup records](https://github.com/emberjs/data/blob/v1.13.5/packages/ember-data/lib/system/store.js#L1375).

Since there is already an issue on Ember Data 1.13, I will close this one.
