### ISSUE TITLE
[ELA <2.1] loadRelationships() should use the relation adapter instead of self

### ISSUE THREAD

**Issue by sebweaver** [genkgo/ember-localforage-adapter#46]
On lines https://github.com/genkgo/ember-localforage-adapter/blob/v2.0.0/addon/adapters/localforage.js#L338-L342

The adapter specialized for the model of the current relationship should be use instead of `this` which represents the adapter of the current model.

I'm about to create a PR for this.

**Comment by sebweaver** [comment]
Pending fix: https://github.com/genkgo/ember-localforage-adapter/compare/v1.13.1...sebweaver:issue-46

**Comment by frederikbosch** [comment]
@sebweaver Merged, and tagged 1.13.2. Thanks!
