### ISSUE TITLE
Create a branch for continuing support of version 1.13.x

### ISSUE THREAD

**Issue by sebweaver** [genkgo/ember-localforage-adapter#47]
Since ED 2.0 (and future ELA 2.1) contains some breaking changes and unsupported deprecations, some users may be unable, or unwilling, to migrate.

That's why I think ELA 1.13 should be still maintained, at least for a while, and a branch should be created in order to continue creating PR on it.

For example, I've create a fix for #46 which is: https://github.com/genkgo/ember-localforage-adapter/compare/v1.13.1...sebweaver:issue-46 and I'd like to create the corresponding PR.

I would also want to add these this [workaround](https://github.com/genkgo/ember-localforage-adapter/blob/v2.0.0/addon/serializers/localforage.js#L19-L40) into another PR, which could benefit to users of ELA 1.13 too.

What do you think?

**Comment by frederikbosch** [comment]
Agreed. We also did that when switching to Ember CLI Addon. Will take action after holidays (next Thursday).

**Comment by frederikbosch** [comment]
Done, see [branch ember-113-compat](https://github.com/genkgo/ember-localforage-adapter/tree/ember-113-compat).
