### ISSUE TITLE
Compat Ember Data 2.1

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/ember-localforage-adapter#51]
@sebweaver Just saw your commits. Are we ready for a new release?

**Comment by sebweaver** [comment]
Unless I missed something, or if you want to discuss these commits, I would say yes!

**Comment by frederikbosch** [comment]
Just released version 2.1.1 of ELA. I believe I made a mistake with version 2.0.0 (which cannot be undone in `npm`), so I had to release 2.1.1 as well. Sorry for that.

**Comment by frederikbosch** [comment]
You might want to include your name in the list of authors in `bower.json`. Since I do not know if you want that, and if so what e-mail address you want to include, I cannot do this for you. But it would be fair anyway!
