### ISSUE TITLE
Compat Ember Data 2.2

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/ember-localforage-adapter#54]
Investigate whether upgrade is without problems. Release new version 2.2 of adapter.

**Comment by sebweaver** [comment]
In https://github.com/genkgo/ember-localforage-adapter/issues/51 you said:

> You might want to include your name in the list of authors in bower.json. Since I do not know if you want that, and if so what e-mail address you want to include, I cannot do this for you. But it would be fair anyway!

My bad, I never answered. So yes, I agree:

    Sébastien Tisserant <s.tisserant@gmail.com>

Thanks!
