### ISSUE TITLE
CRUD: changes in bulk

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/ember-localforage-adapter#6]
Test 44 fails.

**Comment by frederikbosch** [comment]
@arenoir Do you know how to do this?

**Comment by arenoir** [comment]
I am planning on rewriting some of the tests this one especially.  They are quite fragile right now.

**Comment by frederikbosch** [comment]
@arenoir Sorry, my reply supposed to be for the already closed bug #7. I will investigate how to fix this particular test. If you plan to rewrite test: go ahead!
