### ISSUE TITLE
Caching remote data

### ISSUE THREAD

**Issue by borisrorsvort** [genkgo/ember-localforage-adapter#62]
Hi, would there be a way to use this addon to cache remote data from an api.
There was this project but its doesnt seems very much maintained: https://github.com/api-hogs/ember-data-offline

**Comment by frederikbosch** [comment]
@borisrorsvort I that case I think I'd go for service workers. Maybe [this package](https://github.com/jkleinsc/broccoli-serviceworker) is interesting.
