### ISSUE TITLE
add built dist folder on npm package

### ISSUE THREAD

**Issue by maruilian11** [genkgo/ember-localforage-adapter#63]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider adding built dist folder to npm package so that we can use **npm package auto-update config** to add every released version to cdnjs **automatically** with building.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7134

**Comment by frederikbosch** [comment]
@maruilian11 How should I build it? I have never done that before. Please give me the exact commands, otherwise I might not be able to help you.

**Comment by maruilian11** [comment]
hi @frederikbosch, sorry for not noticing the reply.
please take a look at https://github.com/cdnjs/cdnjs/issues/7134#issuecomment-235141792

**Comment by maruilian11** [comment]
if that is not enough, I'm happy to ask the building step for it.
