### ISSUE TITLE
getting init issue in safari

### ISSUE THREAD

**Issue by sankar-ganesh** [genkgo/ember-localforage-adapter#69]
On initial load or when user come back after clearing the local store we see init problem only in web safari browser.

On init we are trying to set default values into the indexDB. Appreciate your help!!! Thanks

PS: No error in browser console

**Comment by frederikbosch** [comment]
This needs more clarification. Show me something of your code. What Ember version are you on? What version of the adapter?

**Comment by sankar-ganesh** [comment]
This is the adapter

```
import Ember from 'ember';
import LFAdapter from 'ember-localforage-adapter/adapters/localforage';

const {
  computed,
  inject
} = Ember;

export default LFAdapter.extend({
  session: inject.service('session'),

  namespace: computed('session.appId', {
    get: function() {
      var appId = this.get('session.appId');
      return appId && appId.toString();
    }
  }),

  caching: 'all'
});
```

In route I am doing this

```
model: function() {
    return this.store.findAll("datastore");
},

afterModel: function(model) {
   var session = this.get('session.appId'), 
         datastore = model && model.findBy("appId", appId);
   if (datastore) {
      // data available
   } else {
      // load datastore
      datastore = this.store.createRecord('datastore', {
               appId: appId,
               messages: Ember.A([])
     });
     return datastore.save();
   }
}
```

**Comment by frederikbosch** [comment]
What if you add localforage to your bower.json with version 1.5.0? Maybe there is a bug fixed for safari.

**Comment by frederikbosch** [comment]
If so, we could update this package to reference a newer localforage version.

**Comment by sankar-ganesh** [comment]
works like a champ :-) thanks!!!

shall we continue pointing to 1.5.0?

**Comment by frederikbosch** [comment]
Yeah, if you could create a PR with the new version, that would be great.

**Comment by sankar-ganesh** [comment]
Thanks, I will create a PR with the new version.

what would be the response here, if indexdb is not supported or failed to load by the browser

**Comment by frederikbosch** [comment]
Locaforage updated to latest version, closed.
