### ISSUE TITLE
Deprecation: _shouldSerializeHasMany

### ISSUE THREAD

**Issue by d-schloss-mvg** [genkgo/ember-localforage-adapter#70]
With ember-data 2.12 the method `_shouldSerializeHasMany` has been deprecated and promoted to public API `shouldSerializeHasMany`

<pre>
DEPRECATION: The private method _shouldSerializeHasMany has been promoted to the public API. Please remove the underscore to use the public shouldSerializeHasMany method. [deprecation id: ds.serializer.private-should-serialize-has-many]
</pre>

**Comment by frederikbosch** [comment]
@d-schloss-mvg Could you create a PR for this?

**Comment by d-schloss-mvg** [comment]
I created a pull request, but obviously this works only for newer ember-data-versions where _shouldSerializeHasMany is already available without underscore.

**Comment by d-schloss-mvg** [comment]
Updated pull request #71 @frederikbosch

**Comment by frederikbosch** [comment]
Will have a look soon! Thanks @d-schloss-mvg

**Comment by johnunclesam** [comment]
Any news on this?
