### ISSUE TITLE
Can I observe to IndexDB updates

### ISSUE THREAD

**Issue by sankar-ganesh** [genkgo/ember-localforage-adapter#72]
Is there a way I can observe to IndexDB actions like 'add', 'update', or 'delete'

**Comment by frederikbosch** [comment]
Nope, why would you want to?

**Comment by sankar-ganesh** [comment]
To keep multiple tabs that are open to be in sync?

**Comment by frederikbosch** [comment]
Something like this should work. Requires [localForage observerable](https://github.com/localForage/localForage-observable) and a little extension to the default adapter to start observing.

```js
import LFAdapter from 'ember-localforage-adapter/adapters/localforage';

export default LFAdapter.extend({

  startObserveringIndexDb: Ember.on('init', function () {
    var observable = window.localforage.newObservable();
    var subscription = observable.subscribe({
      next: function(args) {
        console.log('I observe everything', args);
      },
      error: function(err) {
        console.log('Found an error!', err);
      },
      complete: function() {
        console.log('Observable destroyed!');
      }
    });
  })

});
```

**Comment by sankar-ganesh** [comment]
I couldn't find window.localforage.newObservable

**Comment by frederikbosch** [comment]
@sankar-ganesh See that link I posted in the previous message. You will need an additional library.

**Comment by sankar-ganesh** [comment]
As these dependencies are not compatible like an addon ember build doesn't allow me to build it together with the app. By any chance, can i reload the datastore completely to get all of the latest value instead of observing it.

**Comment by frederikbosch** [comment]
Why not? You can use

```js
app.import('bower_components/x/y.js');
```

to import external libraries that you installed with bower.

**Comment by sankar-ganesh** [comment]
BTW, the zen-observer and localforage-observable are not bower components either

**Comment by frederikbosch** [comment]
Then copy the distributable to your vendor folder.

**Comment by sankar-ganesh** [comment]
that's right but then it doesn't serve the deployment rules. Instead they have either served the es6 version or the dist folder which can't be used via app.import

**Comment by frederikbosch** [comment]
Fair enough. Then you should create a PR that adds the feature here. I am prepared to merge it.
