### ISSUE TITLE
Deprecation: ember-cli-version-checker since 2.18

### ISSUE THREAD

**Issue by d-schloss-mvg** [genkgo/ember-localforage-adapter#73]
Starting a project (ember 2.18) with `ember-localforage-adapter` in package.json gets the following error on `ember serve`:

```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   at DependencyVersionChecker.NPMDependencyVersionChecker (/my-project/node_modules/ember-localforage-adapter/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)
```

Updating to ember-cli-version-checker ^2.0.0 will mitigate this error.

See here: https://github.com/ember-cli/ember-cli-version-checker/issues/48

**Comment by Driezzz** [comment]
I ge the same warning. It would also be nice to remove the bower dependency "localforage" since ember is moving away from bower_components.

**Comment by frederikbosch** [comment]
See master branch.
