### ISSUE TITLE
Request: remove bower_component "localforage" as dependency

### ISSUE THREAD

**Issue by Driezzz** [genkgo/ember-localforage-adapter#74]
When performing `ember install ember-localforage-adapter`

it also installs a bower_component called 'localforage', woudl it be possible to remove this as a dependency? Or there any alternatives?

**Comment by frederikbosch** [comment]
Driezzz, would you able to create a PR for this?

**Comment by Driezzz** [comment]
@frederikbosch I'll try.

**Comment by NullVoxPopuli** [comment]
Here is a hack:
```js
// ember-cli-build.js
app.import('node_modules/localforage/dist/localforage.js', {
    using: [{ transformation: 'cjs', as: 'localforage' }]
  });
```

```bash
mkdir -p bower_components
cd bower_components
ln -s ../node_modules/localforage localforage
```

but, it looks like I can't use the adapter anyway due to no module unification support. :-\

**Comment by frederikbosch** [comment]
See master branch.
