### ISSUE TITLE
Two new deprecations

### ISSUE THREAD

**Issue by Driezzz** [genkgo/ember-localforage-adapter#76]
Two new deprecations have occured:

`Use of @ember/Map is deprecated. Please use native `Map` instead [deprecation id: ember-map-deprecation]`

This warning occurs in the file **/utils/cache**

`data: _ember['default'].Map.create(),`

-----------------------------------------------------

`Use of @ember/OrderedSet is deprecated. Please use native `Map` instead [deprecation id: ember-map-deprecation]`

This warning occurs in the same file **/utils/cache** but deeper in the code **@ember/map/lib/ordered-set**

**Comment by frederikbosch** [comment]
See master branch.
