### ISSUE TITLE
Disabling cache in testing or clearing the cache between tests?

### ISSUE THREAD

**Issue by NullVoxPopuli** [genkgo/ember-localforage-adapter#77]
I ran in to an issue between tests when I upgraded today (to beta.4), where having the cache no by default (previous version I was using didn't have cache), records were mistakenly being kept between tests.

I have this at the moment
```ts
import localforage from 'localforage';

async function cleanEverything() {
  // specifically, offline storage
  await localforage.clear();
  await localStorage.clear();
}

export function clearLocalStorage(hooks: NestedHooks) {
  hooks.beforeEach(async function() {
    await cleanEverything();
  });

  hooks.afterEach(async function() {
    await cleanEverything();
  });
}
```

with

```ts
export default LFAdapter.extend({
  namespace: 'emberclear',
  caching: 'none',
  // ...
```

and that gets all my tests passing! :tada: 

but for having cache, (cause I assume this would make overall app usage slightly quicker?), 
I need a way to clear the cache between tests such that the same behavior as my `cleanEverything` function will still work -- is there a way to do this? (or is this a coming feature?)

**Comment by frederikbosch** [comment]
The way I did it yesterday.

1. [call setupTest(hooks)](https://github.com/genkgo/ember-localforage-adapter/blob/master/tests/integration/crud-test.js#L34).
2. [in each test, lookup the adapter in the container](https://github.com/genkgo/ember-localforage-adapter/blob/master/tests/integration/crud-test.js#L43).
3. [in each test, clear the cache](https://github.com/genkgo/ember-localforage-adapter/blob/master/tests/integration/crud-test.js#L44).

Maybe wrap in a function.
